services:
  nest-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '5001:5001'
    environment:
      NODE_ENV: production

    command: ["sh", "-c", "npx prisma migrate deploy && npx prisma generate && node dist/src/main.js"]
  next-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

    command: ["npm", "start"]

  db:
    image: postgres:latest
    container_name: gazin-tech-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gazin-tech
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
