services:
  nest-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '3000:3000'
    command: ["sh", "-c", "npx prisma migrate deploy && npx prisma generate && npx prisma db seed && npm run start"]

  db:
    image: postgres:latest
    container_name: gazin-tech-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gazin-tech
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
